{"error":"password authentication failed for user \"root\"","level":"error","message":"Error in endpoint","service":"3d-measurement-api","stack":"error: password authentication failed for user \"root\"\n    at /root/3d-measurement-app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///root/3d-measurement-app/api-server/src/index.js:158:22","timestamp":"2025-06-27T16:56:42.837Z"}
{"error":"password authentication failed for user \"root\"","level":"error","message":"Error in endpoint","service":"3d-measurement-api","stack":"error: password authentication failed for user \"root\"\n    at /root/3d-measurement-app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///root/3d-measurement-app/api-server/src/index.js:158:22","timestamp":"2025-06-27T16:57:22.995Z"}
{"error":"password authentication failed for user \"root\"","level":"error","message":"Error in endpoint","service":"3d-measurement-api","stack":"error: password authentication failed for user \"root\"\n    at /root/3d-measurement-app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///root/3d-measurement-app/api-server/src/index.js:158:22","timestamp":"2025-06-27T16:57:32.328Z"}
{"error":"password authentication failed for user \"root\"","level":"error","message":"Error in endpoint","service":"3d-measurement-api","stack":"error: password authentication failed for user \"root\"\n    at /root/3d-measurement-app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///root/3d-measurement-app/api-server/src/index.js:158:22","timestamp":"2025-06-27T17:05:09.525Z"}
{"error":"password authentication failed for user \"root\"","level":"error","message":"Error in endpoint","service":"3d-measurement-api","stack":"error: password authentication failed for user \"root\"\n    at /root/3d-measurement-app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///root/3d-measurement-app/api-server/src/index.js:158:22","timestamp":"2025-06-27T17:07:19.677Z"}
{"error":"password authentication failed for user \"root\"","level":"error","message":"Error in endpoint","service":"3d-measurement-api","stack":"error: password authentication failed for user \"root\"\n    at /root/3d-measurement-app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///root/3d-measurement-app/api-server/src/index.js:162:22","timestamp":"2025-06-27T17:08:37.908Z"}
{"error":"password authentication failed for user \"root\"","level":"error","message":"Error in endpoint","service":"3d-measurement-api","stack":"error: password authentication failed for user \"root\"\n    at /root/3d-measurement-app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///root/3d-measurement-app/api-server/src/index.js:165:22","timestamp":"2025-06-27T17:08:58.680Z"}
{"error":"password authentication failed for user \"root\"","level":"error","message":"Error in endpoint","service":"3d-measurement-api","stack":"error: password authentication failed for user \"root\"\n    at /root/3d-measurement-app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///root/3d-measurement-app/api-server/src/index.js:165:22","timestamp":"2025-06-27T17:09:58.005Z"}
{"error":"password authentication failed for user \"root\"","level":"error","message":"Error in endpoint","service":"3d-measurement-api","stack":"error: password authentication failed for user \"root\"\n    at /root/3d-measurement-app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///root/3d-measurement-app/api-server/src/index.js:165:22","timestamp":"2025-06-27T17:11:28.613Z"}
{"error":"password authentication failed for user \"root\"","level":"error","message":"Error in endpoint","service":"3d-measurement-api","stack":"error: password authentication failed for user \"root\"\n    at /root/3d-measurement-app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///root/3d-measurement-app/api-server/src/index.js:165:22","timestamp":"2025-06-27T17:11:59.648Z"}
{"error":"password authentication failed for user \"root\"","level":"error","message":"Error in endpoint","service":"3d-measurement-api","stack":"error: password authentication failed for user \"root\"\n    at /root/3d-measurement-app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///root/3d-measurement-app/api-server/src/index.js:165:22","timestamp":"2025-06-27T17:12:03.287Z"}
{"error":"password authentication failed for user \"root\"","level":"error","message":"Error in endpoint","service":"3d-measurement-api","stack":"error: password authentication failed for user \"root\"\n    at /root/3d-measurement-app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///root/3d-measurement-app/api-server/src/index.js:165:22","timestamp":"2025-06-27T17:12:04.211Z"}
{"error":"password authentication failed for user \"root\"","level":"error","message":"Error in endpoint","service":"3d-measurement-api","stack":"error: password authentication failed for user \"root\"\n    at /root/3d-measurement-app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///root/3d-measurement-app/api-server/src/index.js:165:22","timestamp":"2025-06-27T17:12:06.259Z"}
{"error":"insert or update on table \"orders\" violates foreign key constraint \"orders_company_id_fkey\"","level":"error","message":"Error in endpoint","service":"3d-measurement-api","stack":"error: insert or update on table \"orders\" violates foreign key constraint \"orders_company_id_fkey\"\n    at /root/3d-measurement-app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///root/3d-measurement-app/api-server/src/index.js:277:20","timestamp":"2025-06-27T17:42:03.579Z"}
{"error":"connect ECONNREFUSED 127.0.0.1:5432","level":"error","message":"Error in endpoint","service":"3d-measurement-api","stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /root/3d-measurement-app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///root/3d-measurement-app/api-server/src/index.js:187:22","timestamp":"2025-06-28T03:51:38.111Z"}
{"error":"connect ECONNREFUSED 127.0.0.1:5432","level":"error","message":"Error in endpoint","service":"3d-measurement-api","stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /root/3d-measurement-app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///root/3d-measurement-app/api-server/src/index.js:187:22","timestamp":"2025-06-28T03:51:47.282Z"}
{"error":"connect ECONNREFUSED 127.0.0.1:5432","level":"error","message":"Error in endpoint","service":"3d-measurement-api","stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at /root/3d-measurement-app/node_modules/pg-pool/index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///root/3d-measurement-app/api-server/src/index.js:187:22","timestamp":"2025-06-28T03:51:55.263Z"}
{"error":"relation \"measurement_templates\" does not exist","furnitureType":"sofa","level":"error","message":"Failed to get measurement template","service":"3d-measurement-api","timestamp":"2025-06-28T03:52:50.465Z"}
{"error":"column \"furniture_type\" of relation \"orders\" does not exist","level":"error","message":"Photo upload failed","orderId":"687121bd-394d-4c3b-b500-4991c033eceb","service":"3d-measurement-api","timestamp":"2025-06-28T04:12:12.040Z","user":"admin@acme.com"}
{"error":"value too long for type character varying(500)","level":"error","message":"Photo upload failed","orderId":"687121bd-394d-4c3b-b500-4991c033eceb","service":"3d-measurement-api","timestamp":"2025-06-28T04:12:39.852Z","user":"admin@acme.com"}
